name: DevSecOps Pipeline

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  devsecops-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run SCA scan (npm audit)
        run: |
          npm install
          npm audit --audit-level=high || true
        continue-on-error: true

      - name: Run SAST scan (Semgrep)
        uses: semgrep/semgrep-action@v1
        with:
          config: "p/default"
        continue-on-error: true

      - name: Run Secrets scan (Gitleaks)
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true

      - name: Build Docker image
        run: docker build -t klonekv55/oso-projekt:latest .

      - name: Run Container scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'klonekv55/oso-projekt:latest'
          format: 'table'
          severity: 'HIGH,CRITICAL'
        continue-on-error: true

      - name: Run DAST scan (OWASP ZAP)
        run: |
          mkdir -p zap-report
          docker run --rm --name juice-shop-dast -d -p 3000:3000 klonekv55/oso-projekt:latest
          sleep 20
          IP_ADDRESS=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' juice-shop-dast)
          echo "Juice Shop running at IP: $IP_ADDRESS"
          docker run --rm -v $(pwd)/zap-report:/zap/wrk/:rw owasp/zap2docker-stable zap-baseline.py -t http://$IP_ADDRESS:3000 -g gen.conf -J zap-report.json
        continue-on-error: true

      - name: Push image to Docker Hub
        run: docker push klonekv55/oso-projekt:latest
